<!doctype html>
<html>
    <head>
        <title>АС ЭКЗАМЕНТАТОР</title>
        <!-- Bootstrap -->
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link href="/css/bootstrap.min.css" rel="stylesheet">
        <!--[if lte IE 9]>
            <script src="/js/html5shiv.js"></script>
            <script src="/js/respond.min.js"></script>
        <![endif]-->
        <script src="/js/jquery-1.12.3.min.js"></script>
        <script src="/js/bootstrap.min.js"></script>


    </head>
    <body>
        <div class="header" style="background: url(/img/head.jpg) 100% 100% no-repeat; background-size:cover; height: 80px;">
            <div class="container"> 
                <div class="col-sm-11">
                    <span class="text-center"><h1 class="text-info"><strong><em>АС "ЭКЗАМЕНАТОР"</em></strong></h1></span>
                </div>
            </div>
        </div>
        <div class="container">

            <?= $this->layout()->content ?>


            <!--Информация-->
            <div class="clearfix"></div>
            <div class="col-sm-6 col-sm-offset-4 text-left">
                <div class="text-danger "> <del>Создать форму записи типов подразделения к отделению для админа</del></div>
                <div class="text-danger "><del> Создать механизм и форму переименования сущностей</del></div>
                <div class="text-danger "><del>Корректный выход пользователя с сообщением при входе в админ-панель</del></div>
                <div class="text-danger "><del>для админа создать пункт меню "типы предприятий" для вывода всех</del> </div>
                <div class="text-danger "><del>"типы предприятий"  - CRUD  операции </del> </div>
                <div class="text-danger "><del>"расписание отделения"  -  какие функции сего пункта? привилегии </del> </div>
                <div class="text-danger "><del>"расписание"  - CRUD  операции </del> </div>
                <div class="text-danger "><del>"Вывод результатов, сохранение в текстовой форме в бд  </del> </div>
                <div class="text-danger "><del>"Вывод сообщений- подсказок "  </del> </div>
                <div class="text-danger "><del>"Сдача экзаменов по индивидуальному паролю, общему паролю "  </del> </div>
                <div class="text-danger "><del>"Множественный выбор предприятий в расписании "  </del> </div>
                <div class="text-danger "><del>"Все предприятия отделения  - в расписании"  </del> </div>
                <div class="text-danger "><del>"необязательные поля в профиле пользователя (login,passw)"  </del> </div>
            </div>


        </div>





    </body>

