<!doctype html>
<html>
    <head>
        <title>АС ЭКЗАМЕНТАТОР</title>
        <!-- Bootstrap -->
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link href="/css/bootstrap.min.css" rel="stylesheet">
        <!--[if lte IE 9]>
            <script src="/js/html5shiv.js"></script>
            <script src="/js/respond.min.js"></script>
        <![endif]-->
        <script src="/js/jquery-1.12.3.min.js"></script>
        <script src="/js/bootstrap.min.js"></script>


    </head>
    <body>

        <div class="header" style="background: url(/img/head.jpg) 100% 100% no-repeat; background-size:cover; height: 80px;">
            <div class="container"> 
                <div class="col-sm-11">
            <span class="text-center"><h1 class="text-info"><strong><em>АС "ЭКЗАМЕНАТОР"</em></strong></h1></span>
                </div>
               
            </div>
        </div>


        <div class="container">
<!--            <div class="col-sm-5 col-md-offset-3">-->
                <p>&nbsp</p>
                <?= $this->layout()->content ?>
<!--            </div>-->

            <!--Информация-->
            <div class="clearfix"></div>

           
        

    </div>





</body>

