<!doctype html>
<html>
    <head>

        <!-- Bootstrap -->
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <!--<link href="/css/bootstrap.min.css" rel="stylesheet">-->
        <!--[if lte IE 9]>
            <script src="/js/html5shiv.js"></script>
            <script src="/js/respond.min.js"></script>
        <![endif]-->
        <script src="/js/jquery-1.12.3.min.js"></script>
        <script src="/js/bootstrap.min.js"></script>


    </head>
    <body><?= $this->layout()->content ?></body>
</html>

